exports.PetModeShopConfig = {
	"ball": {
		"Poke Ball": -1,
		"Great Ball": 1,
		"Ultra Ball": 2,
		"Master Ball": 200
	},
	"draw": {
		"Strawberry Sweet": 40,
		"Clover Sweet": 40,
		"Berry Sweet": 40,
		"Flower Sweet": 40,
		"Love Sweet": 40,
		"Ribbon Sweet": 40,
		"Star Sweet": 40,
		"Chipped Pot": 40,
		"Cracked Pot": 40,
		"Deep Sea Scale": 40,
		"Deep Sea Tooth": 40,
		"Dragon Scale": 40,
		"Up-Grade": 40,
		"Dubious Disc": 40,
		"Galarica Cuff": 40,
		"Galarica Wreath": 40,
		"Magmarizer": 40,
		"Electirizer": 40,
		"Protector": 40,
		"Prism Scale": 40,
		"Dawn Stone": 40,
		"Dusk Stone": 40,
		"Fire Stone": 40,
		"Ice Stone": 40,
		"Leaf Stone": 40,
		"Moon Stone": 40,
		"Oval Stone": 40,
		"Shiny Stone": 40,
		"Sun Stone": 40,
		"Thunder Stone": 40,
		"Water Stone": 40,
		"King's Rock": 40,
		"Metal Coat": 40,
		"Razor Claw": 40,
		"Razor Fang": 40,
		"Reaper Cloth": 40,
		"Sweet Apple": 40,
		"Tart Apple": 40,
		"Whipped Dream": 40,
		"Sachet": 40,
	},
	"berry": {
		"Aguav Berry": 50,
		"Apicot Berry": 50,
		"Aspear Berry": 50,
		"Babiri Berry": 50,
		"Belue Berry": 50,
		"Bluk Berry": 50,
		"Charti Berry": 50,
		"Cheri Berry": 50,
		"Chesto Berry": 50,
		"Chilan Berry": 50,
		"Chople Berry": 50,
		"Coba Berry": 50,
		"Colbur Berry": 50,
		"Cornn Berry": 50,
		"Custap Berry": 50,
		"Durin Berry": 50,
		"Enigma Berry": 50,
		"Figy Berry": 50,
		"Ganlon Berry": 50,
		"Grepa Berry": 50,
		"Haban Berry": 50,
		"Hondew Berry": 50,
		"Iapapa Berry": 50,
		"Jaboca Berry": 50,
		"Kasib Berry": 50,
		"Kebia Berry": 50,
		"Kee Berry": 50,
		"Kelpsy Berry": 50,
		"Lansat Berry": 50,
		"Leppa Berry": 50,
		"Liechi Berry": 50,
		"Lum Berry": 50,
		"Mago Berry": 50,
		"Magost Berry": 50,
		"Maranga Berry": 50,
		"Micle Berry": 50,
		"Nanab Berry": 50,
		"Nomel Berry": 50,
		"Occa Berry": 50,
		"Oran Berry": 50,
		"Pamtre Berry": 50,
		"Passho Berry": 50,
		"Payapa Berry": 50,
		"Pecha Berry": 50,
		"Persim Berry": 50,
		"Petaya Berry": 50,
		"Pinap Berry": 50,
		"Pomeg Berry": 50,
		"Qualot Berry": 50,
		"Rabuta Berry": 50,
		"Rawst Berry": 50,
		"Razz Berry": 50,
		"Rindo Berry": 50,
		"Roseli Berry": 50,
		"Rowap Berry": 50,
		"Salac Berry": 50,
		"Shuca Berry": 50,
		"Sitrus Berry": 50,
		"Spelon Berry": 50,
		"Starf Berry": 50,
		"Tamato Berry": 50,
		"Tanga Berry": 50,
		"Wacan Berry": 50,
		"Watmel Berry": 50,
		"Wepear Berry": 50,
		"Wiki Berry": 50,
		"Yache Berry": 50,
		"Bitter Berry": 50,
		"Burnt Berry": 50,
		"Gold Berry": 50,
		"Ice Berry": 50,
		"Mint Berry": 50,
		"Miracle Berry": 50,
		"Mystery Berry": 50.
	},
	"battle": {
		"Leftovers": 100,
		"Heavy-Duty Boots": 100,
		"Choice Band": 100,
		"Choice Scarf": 100,
		"Choice Specs": 100,
		"Eviolite": 100,
		"Assault Vest": 100,
		"Rocky Helmet": 100,
		"Protective Pads": 100,
		"Life Orb": 100,
		"Focus Sash": 100,
		"Black Sludge": 100,
		"Light Clay": 100,
		"Weakness Policy": 100,
		"Heat Rock": 50,
		"Damp Rock": 50,
		"Smooth Rock": 50,
		"Icy Rock": 50,
		"Grassy Seed": 50,
		"Electric Seed": 50,
		"Psychic Seed": 50,
		"Misty Seed": 50,
		"Toxic Orb": 50,
		"Flame Orb": 50,
		"Silk Scarf": 50,
		"Miracle Seed": 50,
		"Charcoal": 50,
		"Mystic Water": 50,
		"Magnet": 50,
		"Never-Melt Ice": 50,
		"Hard Stone": 50,
		"Sharp Beak": 50,
		"Soft Sand": 50,
		"Silver Powder": 50,
		"Poison Barb": 50,
		"Black Belt": 50,
		"Spell Tag": 50,
		"Twisted Spoon": 50,
		"Black Glasses": 50,
		"Dragon Fang": 50,
		"Metal Coat": 40,
		"Pixie Plate": 50,
		"Terrain Extender": 50,
		"Expert Belt": 50,
		"Throat Spray": 50,
		"Metronome": 50,
		"Quick Claw": 50,
		"Bright Powder": 50,
		"King's Rock": 40,
		"Shed Shell": 50,
		"Air Balloon": 50,
		"Red Card": 50,
		"Eject Button": 50,
		"Eject Pack": 50,
		"Razor Claw": 40,
		"Razor Fang": 40,
		"Room Service": 50,
		"Safety Goggles": 50,
		"Ring Target": 50,
		"Sticky Barb": 50,
		"Iron Ball": 50,
		"Lagging Tail": 50,
		"Adrenaline Orb": 50,
		"Blunder Policy": 50,
		"Utility Umbrella": 50,
		"Mental Herb": 50,
		"White Herb": 50,
		"Power Herb": 50,
		"Shell Bell": 50,
		"Wide Lens": 50,
		"Scope Lens": 50,
		"Zoom Lens": 50,
		"Berry Juice": 50,
		"Big Root": 50,
		"Binding Band": 50,
		"Destiny Knot": 50,
		"Grip Claw": 50,
		"Float Stone": 20,
		"Focus Band": 20,
		"Muscle Band": 20,
		"Wise Glasses": 20,
		"Absorb Bulb": 20,
		"Cell Battery": 20,
		"Luminous Moss": 20,
		"Snowball": 20,
	},
	"special": {
		"Quick Powder": 10,
		"Metal Powder": 10,
		"Light Ball": 50,
		"Lucky Punch": 50,
		"Thick Club": 50,
		"Leek": 50,
		"Deep Sea Scale": 40,
		"Deep Sea Tooth": 40,
		"Blue Orb": 50,
		"Red Orb": 50,
		"Soul Dew": 50,
		"Adamant Orb": 50,
		"Lustrous Orb": 50,
		"Griseous Orb": 50,
		"Burn Drive": 20,
		"Chill Drive": 20,
		"Douse Drive": 20,
		"Shock Drive": 20,
		"Rusted Sword": 50,
		"Rusted Shield": 50,
	},
	"util": {
		// "Rusty Bottle Cap": 2,
		"Rocket Bottle Cap": 10,
		"Bottle Cap": 25,
		"Gold Bottle Cap": 100,
		"Ability Capsule": 25,
		// "Ability Patch": 100,
		"Nature Mint": 50,
		"Box": 50
	}
}